language: python

os:
  - linux
  - osx
  - windows

sudo: off

python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  pip install -r requirements.txt

script:
  - monnalisa --version
